AppDebug: true

HttpServer:
  Api:
    Port: ":20191"
  Web:
    Port: ":8090"
  AllowCrossDomain: true
  TrustProxies:
    IsOpen: 0
    ProxyServerList:
      - "192.168.10.1"
      - "192.168.10.2"
GrpcServer:
  Port: ":20202"

Token:
  JwtTokenSignKey: "ginskeleton"
  JwtTokenOnlineUsers: 10
  JwtTokenCreatedExpireAt: 28800
  JwtTokenRefreshAllowSec: 86400
  JwtTokenRefreshExpireAt: 36000
  BindContextKeyName: "userToken"
  IsCacheToRedis: 0

Redis:
  Host: "127.0.0.1"
  Port: 6379
  Auth: ""
  MaxIdle: 10
  MaxActive: 1000
  IdleTimeout: 60
  IndexDb: 1
  ConnFailRetryTimes: 3
  ReConnectInterval: 1

Logs:
  GinLogName: "/storage/logs/gin.log"
  ginskeletonLogName: "/storage/logs/ginskeleton.log"
  TextFormat: "json"
  TimePrecision: "millisecond"
  MaxSize: 10
  MaxBackups: 7
  MaxAge: 15
  Compress: false

Websocket:
  Start: 0
  WriteReadBufferSize: 20480
  MaxMessageSize: 65535
  PingPeriod: 20
  HeartbeatFailMaxTimes: 4
  ReadDeadline: 100
  WriteDeadline: 35

SnowFlake:
  SnowFlakeMachineId: 2

FileUploadSetting:
  Size: 32
  UploadFileField: "file"
  UploadFileSavePath: "/storage/app/uploaded/"
  UploadFileReturnPath: "/public/storage/uploaded/"
  AllowMimeType:
    - "image/jpeg"
    - "image/png"
    - "image/x-icon"
    - "image/bmp"
    - "application/zip"
    - "application/x-gzip"
    - "text/plain; charset=utf-8"
    - "video/mp4"
    - "audio/mpeg"

Casbin:

  IsInit: 0
  AutoLoadPolicySeconds: 5
  TablePrefix: "tb"
  TableName: "auth_casbin_rule"
  ModelConfig: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _ , _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = (g(r.sub, p.sub) || p.sub == "*" ) && keyMatch(r.obj , p.obj) && (r.act == p.act || p.act == "*")

RabbitMq:
  HelloWorld:

    Addr: "amqp://账号:密码@ip地址:5672/"
    QueueName: "helloword_queue"
    Durable: false
    ConsumerChanNumber: 2
    OffLineReconnectIntervalSec: 5
    RetryCount: 5
  WorkQueue:
    Addr: "amqp://账号:密码@ip地址:5672/"
    QueueName: "work_queue"
    Durable: false
    ConsumerChanNumber: 2
    OffLineReconnectIntervalSec: 5
    RetryCount: 5
  PublishSubscribe:
    Addr: "amqp://账号:密码@ip地址:5672/"
    ExchangeType: "fanout"
    ExchangeName: "fanout_exchange"
    DelayedExchangeName: "delayed_fanout_exchange"
    Durable: false
    QueueName: ""
    ConsumerChanNumber: 1
    OffLineReconnectIntervalSec: 10
    RetryCount: 5
  Routing:
    Addr: "amqp://账号:密码@ip地址:5672/"
    ExchangeType: "direct"
    ExchangeName: "direct_exchange"
    DelayedExchangeName: "delayed_direct_exchange"
    Durable: false
    QueueName: ""
    OffLineReconnectIntervalSec: 10
    RetryCount: 5
  Topics:
    Addr: "amqp://账号:密码@ip地址:5672/"
    ExchangeType: "topic"
    ExchangeName: "topic_exchange"
    DelayedExchangeName: "delayed_topic_exchange"
    Durable: false
    QueueName: ""
    OffLineReconnectIntervalSec: 10
    RetryCount: 5

Captcha:
  captchaId: "captcha_id"
  captchaValue: "captcha_value"
  length: 4

