Gormv2:
  UseDbType: "mysql"
  SqlDebug: false
  Mysql:
    IsInitGlobalGormMysql: 0
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3306
      Prefix: "tb_"
      User: "root"
      Pass: "DRsXT5ZJ6Oi55LPQ"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

    IsOpenReadDb: 0
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3308
      Prefix: "tb_"
      User: "root"
      Pass: "yourPassword"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

  SqlServer:

    IsInitGlobalGormSqlserver: 0
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"

      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
    IsOpenReadDb: 0
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

  PostgreSql:
    IsInitGlobalGormPostgreSql: 0
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "Secret2017~"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

    IsOpenReadDb: 0
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
